name: "构建Nodejs"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Nodejs
    env:
      IMAGE_NAME: nodejs
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 设置QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 设置Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: 登陆Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: 构建镜像并推送
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          context: ${IMAGE_NAME}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
            ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:lts