name: "构建PagerMaid"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建PagerMaid
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: nevinee/pagermaid
          dockerFile: pagermaid/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: latest
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
